# ==========================================================
# Smart Home Anomaly Detection Dashboard
# Reads artifacts directly from <repo>/notebooks/ (no duplicate copies):
#     best_model.pkl, feature_columns.pkl
# Reads data directly from <repo>/data/HomeC_cleaned_final.zip.
#     No manual extraction needed.
# Reads data/kpi_summary.json (generated by src/HomeC_preprocess.py) so
#     the KPI Cards & Alert Panel always match the EDA figures, no hardcoding.
#
# Paths are computed from __file__ -> works regardless of the calling directory.
#
# Changes from the previous version:
#   1. CORRECT PREDICTION: loads feature_columns.pkl, builds all columns in
#      the exact training order (kept the same as the previous version).
#   2. Dash 3.x: uses app.run() (not the deprecated app.run_server()).
#   3. AI HYBRID: if GEMINI_API_KEY is set -> real call; otherwise -> rule-based fallback.
#   4. NEW: KPI Cards (Total/Average/Peak/Anomalies), Alert Panel,
#      Smart City Recommendation panel, and 10 interactive Plotly charts
#      (Line, Area, Stacked Area, Correlation Heatmap, Weather Scatter +
#      Regression, Top-5 Bar, Pie, Hourly Bar, Day-of-week Bar, Calendar
#      Heatmap) - all using the same color palette as visualization/*.png to
#      keep the static report images and the interactive dashboard in sync.
# ==========================================================

import os
import json

from dotenv import load_dotenv
load_dotenv()

import numpy as np
import dash
from dash import dcc, html, Input, Output, State
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import joblib

# ---------- 0. Paths relative to this file's location (app/ -> repo root) ----------
APP_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = os.path.dirname(APP_DIR)
NOTEBOOKS_DIR = os.path.join(REPO_DIR, "notebooks")
DATA_DIR = os.path.join(REPO_DIR, "data")

MODEL_PATH = os.path.join(NOTEBOOKS_DIR, "best_model.pkl")
FEATURES_PATH = os.path.join(NOTEBOOKS_DIR, "feature_columns.pkl")
MODEL_METADATA_PATH = os.path.join(NOTEBOOKS_DIR, "model_metadata.json")
FEATURE_DEFAULTS_PATH = os.path.join(NOTEBOOKS_DIR, "feature_defaults.json")
DATA_PATH = os.path.join(DATA_DIR, "HomeC_cleaned_final.zip")
KPI_PATH = os.path.join(DATA_DIR, "kpi_summary.json")
TOP5_PATH = os.path.join(DATA_DIR, "top5_appliances.csv")
CORR_PATH = os.path.join(DATA_DIR, "weather_energy_correlation.csv")

# Consistent color palette - SAME hex values as src/HomeC_preprocess.py
# so the static report charts and this interactive dashboard always agree.
COLOR_ENERGY = "#2E86AB"
COLOR_SOLAR = "#F4A300"
COLOR_ANOMALY = "#E63946"
COLOR_NORMAL = "#8AB17D"
COLOR_MEDIUM = "#F2C14E"
COLOR_HIGH = "#E63946"
APPLIANCE_COLORWAY = px.colors.qualitative.Set2

# ---------- 1. Initialization ----------
app = dash.Dash(__name__)
app.title = "Smart Home Anomaly Detection"

# ---------- 2. Dashboard data ----------
data_status = ""
weather_features_guess = ["temperature", "apparentTemperature", "humidity", "visibility",
                           "pressure", "windSpeed", "cloudCover", "windBearing",
                           "precipIntensity", "dewPoint", "precipProbability"]

def compute_local_anomalies(frame):
    if frame.empty or "use [kW]" not in frame.columns or "datetime" not in frame.columns:
        empty_threshold = pd.Series([], dtype=float)
        return 5.0, empty_threshold, np.zeros(len(frame), dtype=bool)

    use = frame["use [kW]"].astype(float).reset_index(drop=True)
    train_end = int(len(frame) * 0.70)
    train = use.iloc[:train_end]
    train_global_threshold = float(train.mean() + 3 * train.std())

    indexed = frame.set_index("datetime", drop=False)
    prior_use = indexed["use [kW]"].astype(float).shift(1)
    rolling_mean = prior_use.rolling("30D", min_periods=1440).mean()
    rolling_std = prior_use.rolling("30D", min_periods=1440).std()
    local_threshold = (
        rolling_mean.fillna(float(train.mean()))
        + 3 * rolling_std.fillna(float(train.std()))
    ).reset_index(drop=True)
    anomaly_mask = (use > local_threshold).to_numpy()
    return train_global_threshold, local_threshold, anomaly_mask


try:
    df = pd.read_csv(DATA_PATH, low_memory=False)
    df["datetime"] = pd.to_datetime(df["datetime"])

    appliance_cols_guess = [c for c in df.columns if "[kW]" in c and c not in
                             ("use [kW]", "gen [kW]")]
    # prefer the grouped columns already produced by HomeC_preprocess.py
    grouped_cols = [c for c in ["Kitchen [kW]", "Furnace [kW]", "Dishwasher [kW]",
                                 "Home office [kW]", "Fridge [kW]", "Wine cellar [kW]",
                                 "Garage door [kW]", "Barn [kW]", "Well [kW]",
                                 "Microwave [kW]", "Living room [kW]"] if c in df.columns]
    if not grouped_cols:
        grouped_cols = appliance_cols_guess

    weather_cols = [c for c in weather_features_guess if c in df.columns]

    daily_total = df.set_index("datetime").resample("D")[["use [kW]", "gen [kW]"]].sum() / 60.0
    hourly_avg = df.groupby("hour")[["use [kW]"]].mean() if "hour" in df.columns else \
        df.assign(hour=df["datetime"].dt.hour).groupby("hour")[["use [kW]"]].mean()
    dow_avg = df.groupby("dayofweek")[["use [kW]"]].mean() if "dayofweek" in df.columns else \
        df.assign(dayofweek=df["datetime"].dt.dayofweek).groupby("dayofweek")[["use [kW]"]].mean()
    monthly_appl = (df.groupby("month")[grouped_cols].sum() / 60.0 / 1000.0) if "month" in df.columns \
        else pd.DataFrame()

    daily_weather = df.set_index("datetime").resample("D")[
        ["use [kW]", "gen [kW]"] + weather_cols
    ].mean(numeric_only=True)

    threshold, local_threshold, anomaly_mask = compute_local_anomalies(df)
    anomalies = df[anomaly_mask].copy()
    if not anomalies.empty:
        anomalies["threshold_kw"] = local_threshold.loc[anomalies.index].to_numpy()
        anomalies["breach_kw"] = anomalies["use [kW]"] - anomalies["threshold_kw"]
    if grouped_cols:
        anomalies["top_appliance"] = df.loc[anomalies.index, grouped_cols].idxmax(axis=1)

    data_status = ""
except FileNotFoundError:
    df = pd.DataFrame({
        "datetime": pd.date_range("2016-01-01", periods=10, freq="h"),
        "use [kW]": [1] * 10, "gen [kW]": [0.1] * 10, "temperature": [70] * 10,
        "hour": list(range(10)), "dayofweek": [0] * 10, "month": [1] * 10,
    })
    grouped_cols, weather_cols = [], []
    daily_total = df.set_index("datetime")[["use [kW]", "gen [kW]"]]
    hourly_avg = df.groupby("hour")[["use [kW]"]].mean()
    dow_avg = df.groupby("dayofweek")[["use [kW]"]].mean()
    monthly_appl = pd.DataFrame()
    daily_weather = daily_total.copy()
    threshold = 5.0
    anomalies = df.iloc[0:0]
    data_status = (f"{DATA_PATH} not found, plotting placeholder data instead. "
                   f"Run src/HomeC_preprocess.py to regenerate the data ZIP file.")

# ---------- 2b. KPI summary (prefer reading from kpi_summary.json) ----------
try:
    with open(KPI_PATH, "r", encoding="utf-8") as f:
        kpi = json.load(f)
except FileNotFoundError:
    kpi = {
        "total_energy_kwh": round(df["use [kW]"].sum() / 60, 2),
        "average_energy_kw": round(df["use [kW]"].mean(), 4),
        "peak_consumption_kw": round(df["use [kW]"].max(), 4),
        "peak_consumption_time": str(df.loc[df["use [kW]"].idxmax(), "datetime"]),
        "number_of_anomalies": int(len(anomalies)),
        "anomaly_rate_pct": round(len(anomalies) / max(len(df), 1) * 100, 2),
        "anomaly_label_definition": "prior 30-day rolling threshold, current row excluded",
        "anomaly_threshold_kw": round(threshold, 4),
    }

# ---------- 2c. Top-5 appliances (prefer reading from top5_appliances.csv) ----------
try:
    top5_df = pd.read_csv(TOP5_PATH, index_col=0).sort_values("Total_kWh", ascending=False)
except FileNotFoundError:
    if grouped_cols:
        totals = (df[grouped_cols].sum() / 60.0).sort_values(ascending=False)
        top5_df = pd.DataFrame({"Total_kWh": totals, "Share_%": (totals / totals.sum() * 100).round(2)})
    else:
        top5_df = pd.DataFrame({"Total_kWh": [], "Share_%": []})

top5 = top5_df.head(5)
appliance_color_map = {col: APPLIANCE_COLORWAY[i % len(APPLIANCE_COLORWAY)]
                        for i, col in enumerate(top5_df.index)}

# ---------- 2d. Weather-energy correlation (prefer reading from the existing csv) ----------
try:
    corr_daily = pd.read_csv(CORR_PATH, index_col=0)
except FileNotFoundError:
    if weather_cols:
        corr_daily = daily_weather.corr()[["use [kW]", "gen [kW]"]].drop(
            ["use [kW]", "gen [kW]"], errors="ignore")
    else:
        corr_daily = pd.DataFrame()

# ---------- 3. Load model + COLUMN LIST (critical for correct predictions) ----------
try:
    model = joblib.load(MODEL_PATH)
    feature_columns = joblib.load(FEATURES_PATH)
    with open(MODEL_METADATA_PATH, "r", encoding="utf-8") as f:
        model_metadata = json.load(f)
    with open(FEATURE_DEFAULTS_PATH, "r", encoding="utf-8") as f:
        feature_defaults = json.load(f)
    decision_threshold = float(model_metadata.get("decision_threshold", 0.5))
    test_f1 = model_metadata.get("test_metrics", {}).get("F1", "N/A")
    model_status = (f"Model ready: {model_metadata.get('selected_model', 'model')} | "
                    f"{len(feature_columns)} features | test F1={test_f1}.")
except FileNotFoundError:
    model = None
    feature_columns = None
    model_metadata = {}
    feature_defaults = {}
    decision_threshold = 0.5
    model_status = ("Model artifacts not found in notebooks/. Using a simulated prediction. "
                    "Run python src/train_model.py.")

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if GEMINI_API_KEY:
    print("[AI] GEMINI_API_KEY found. Mode: real Gemini.")
else:
    print("[AI] GEMINI_API_KEY NOT found. Mode: rule-based fallback.")


# ---------- 4. AI integration: HYBRID ----------
def _ai_fallback(prediction, temp_val, appliance_val):
    if prediction == 1:
        return (f"[AI - offline mode] ANOMALOUS consumption detected. "
                f"Temperature {temp_val} degrees, total appliance load {appliance_val} kW. "
                f"Suggest checking heating/cooling equipment or a possible power leak.")
    return (f"[AI - offline mode] NORMAL consumption at temperature "
            f"{temp_val} degrees, total appliance load {appliance_val} kW. No signs of anomaly.")


def get_ai_explanation(prediction, temp_val, appliance_val):
    if not GEMINI_API_KEY:
        return _ai_fallback(prediction, temp_val, appliance_val)

    label = "ANOMALOUS" if prediction == 1 else "NORMAL"
    prompt = (
        "You are a smart home energy analysis assistant. "
        f"The model has just classified the power consumption as {label}. "
        f"Context: temperature {temp_val} degrees, total appliances on {appliance_val} kW. "
        "Briefly explain (3-4 sentences) in English why this might be the case "
        "and suggest an action for the user."
    )
    try:
        import requests
        url = ("https://generativelanguage.googleapis.com/v1beta/models/"
               "gemini-2.5-flash-lite:generateContent?key=" + GEMINI_API_KEY)
        resp = requests.post(
            url,
            json={"contents": [{"parts": [{"text": prompt}]}]},
            timeout=15,
        )
        resp.raise_for_status()
        text = resp.json()["candidates"][0]["content"]["parts"][0]["text"]
        return "[AI - Gemini] " + text.strip()
    except Exception as e:
        return _ai_fallback(prediction, temp_val, appliance_val) + f"  (Fallback reason: {e})"


# ---------- 5. Correct prediction function ----------
def predict_anomaly(user_inputs: dict):
    """Return (class, probability/score) using the calibrated validation threshold."""
    if model is None or feature_columns is None:
        temp = float(user_inputs.get("temperature", 0) or 0)
        appl = float(user_inputs.get("total_appliance", 0) or 0)
        pred = 1 if (temp > 80 or appl > 5) else 0
        return pred, float(pred)

    complete = dict(feature_defaults)
    complete.update({k: v for k, v in user_inputs.items() if v is not None})
    row = pd.DataFrame([complete]).reindex(columns=feature_columns)
    if row.isna().any().any():
        missing = row.columns[row.isna().any()].tolist()
        raise ValueError(f"Missing values for features: {missing}")
    if hasattr(model, "predict_proba"):
        score = float(model.predict_proba(row)[:, 1][0])
    else:
        score = float(model.decision_function(row)[0])
    return int(score >= decision_threshold), score


# ==========================================================
# 6. CHARTS (Plotly) - use the same color palette as visualization/*.png
# ==========================================================

# 6.1 Line chart - daily power consumption, full year
fig_line = px.line(daily_total.reset_index(), x="datetime", y="use [kW]",
                    title="Daily Power Consumption (Full Year 2016)",
                    labels={"datetime": "Date", "use [kW]": "Consumption (kWh/day)"})
fig_line.update_traces(line_color=COLOR_ENERGY)
fig_line.add_hline(y=daily_total["use [kW]"].mean(), line_dash="dash", line_color=COLOR_ANOMALY,
                    annotation_text="Yearly average")

# 6.2 Area chart - use vs gen
fig_area = go.Figure()
fig_area.add_trace(go.Scatter(x=daily_total.index, y=daily_total["use [kW]"], name="Consumption (Use)",
                               fill="tozeroy", line_color=COLOR_ENERGY))
fig_area.add_trace(go.Scatter(x=daily_total.index, y=daily_total["gen [kW]"], name="Solar Generation (Gen)",
                               fill="tozeroy", line_color=COLOR_SOLAR))
fig_area.update_layout(title="Power Consumption vs Solar Generation (Daily)",
                        xaxis_title="Date", yaxis_title="Energy (kWh/day)")

# 6.6 Top-5 appliances bar chart
fig_top5 = px.bar(top5.reset_index(), x="index", y="Total_kWh", text="Share_%",
                   color="index", color_discrete_map=appliance_color_map,
                   title="Top 5 Highest-Consuming Appliances (Full Year 2016)",
                   labels={"index": "Appliance", "Total_kWh": "Total Consumption (kWh)"})
fig_top5.update_traces(texttemplate="%{text}%", textposition="outside")
fig_top5.update_layout(showlegend=False)

# 6.7 Pie chart - Top5 vs Others
if not top5_df.empty:
    others_total = top5_df["Total_kWh"].iloc[5:].sum()
    pie_labels = list(top5.index) + (["Others"] if others_total > 0 else [])
    pie_values = list(top5["Total_kWh"]) + ([others_total] if others_total > 0 else [])
    pie_colors = [appliance_color_map.get(c) for c in top5.index] + (["#B0B0B0"] if others_total > 0 else [])
    fig_pie = go.Figure(go.Pie(labels=pie_labels, values=pie_values,
                                marker_colors=pie_colors, hole=0.35))
    fig_pie.update_layout(title="Power Consumption Share by Appliance")
else:
    fig_pie = px.pie(title="No appliance data available")

# 6.8 Hourly consumption (colored by Low/Medium/High level)
low_t, high_t = hourly_avg["use [kW]"].quantile([0.33, 0.66])
hourly_colors = [COLOR_NORMAL if v <= low_t else COLOR_MEDIUM if v <= high_t else COLOR_HIGH
                  for v in hourly_avg["use [kW]"]]
fig_hourly = go.Figure(go.Bar(x=hourly_avg.index, y=hourly_avg["use [kW]"], marker_color=hourly_colors))
fig_hourly.update_layout(title="Average Power Consumption by Hour of Day",
                          xaxis_title="Hour (0-23)", yaxis_title="Avg. Consumption (kW)")

# 6.9 Day-of-week consumption
dow_labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][:len(dow_avg)]
dow_colors = [COLOR_HIGH if d >= 5 else COLOR_ENERGY for d in dow_avg.index]
fig_dow = go.Figure(go.Bar(x=dow_labels, y=dow_avg["use [kW]"], marker_color=dow_colors))
fig_dow.update_layout(title="Average Power Consumption by Day of Week",
                       xaxis_title="Day of Week", yaxis_title="Avg. Consumption (kW)")

# ==========================================================
# 7. ALERT PANEL - anomaly alerts (top N by degree of threshold breach)
# ==========================================================

def build_alert_cards(anomalies_df, threshold_val, max_alerts=5):
    if anomalies_df.empty:
        return [html.Div("No anomalies detected in the current data.",
                          style={"color": COLOR_NORMAL, "fontWeight": "bold"})]

    sort_column = "breach_kw" if "breach_kw" in anomalies_df.columns else "use [kW]"
    top_alerts = anomalies_df.sort_values(sort_column, ascending=False).head(max_alerts)
    cards = []
    for _, row in top_alerts.iterrows():
        row_threshold = float(row.get("threshold_kw", threshold_val))
        appliance_note = (f" Top contributing appliance: {row['top_appliance']}."
                           if "top_appliance" in row and pd.notna(row.get("top_appliance"))
                           else "")
        cards.append(html.Div([
            html.Span("[WARNING] ", style={"color": COLOR_ANOMALY, "fontSize": "18px"}),
            html.B(f"{row['datetime']}"),
            html.Span(f" - Consumption of {row['use [kW]']:.2f} kW exceeded the normal threshold "
                      f"({row_threshold:.2f} kW).{appliance_note}"),
        ], style={"padding": "8px 12px", "borderLeft": f"4px solid {COLOR_ANOMALY}",
                  "backgroundColor": "#FDEDEE", "marginBottom": "6px", "borderRadius": "4px"}))
    return cards


alert_cards = build_alert_cards(anomalies, threshold)


# ==========================================================
# 8. SMART CITY RECOMMENDATION PANEL
# ==========================================================

def build_recommendations(top5_df, corr_daily):
    recs = []
    if not top5_df.empty:
        top_name = top5_df.index[0]
        top_share = top5_df["Share_%"].iloc[0] if "Share_%" in top5_df.columns else None
        if top_share is not None:
            recs.append(f"{top_name} accounts for {top_share}% of total appliance consumption - "
                        f"the top priority for saving power is adjusting this device's operating "
                        f"schedule (e.g., timers, adjusting the set temperature).")
        if "Peak_Hour" in top5_df.columns:
            ph = top5_df["Peak_Hour"].iloc[0]
            recs.append(f"{top_name} runs most heavily around {ph}:00 - "
                        f"part of its operation could be shifted to off-peak hours to reduce load.")

    if isinstance(corr_daily, pd.DataFrame) and "gen [kW]" in corr_daily.columns:
        gen_corr = corr_daily["gen [kW]"].dropna()
        if "temperature" in gen_corr.index:
            recs.append(f"Solar generation correlates with temperature (r={gen_corr['temperature']:.2f}) "
                        f"- high-power appliances should be used as much as possible on warm, sunny "
                        f"days to draw directly from solar power and reduce grid usage.")
        if "cloudCover" in gen_corr.index and gen_corr["cloudCover"] < 0:
            recs.append("Higher cloud cover reduces solar generation - "
                        "the system should automatically switch to an 'energy-saving priority' "
                        "alert on cloudy days.")

    recs.append("Set up automatic scheduling: shift the Dishwasher/Microwave to off-peak hours "
               "(nighttime or midday when sunny) to reduce peak-hour electricity costs.")
    recs.append("When the system reports repeated anomaly alerts from a single device, "
               "send a Smart City notification so the user can inspect the device (risk of "
               "malfunction/electrical leakage).")
    return recs[:6]


recommendations = build_recommendations(top5_df, corr_daily)


# ==========================================================
# 9. KPI CARDS
# ==========================================================

def kpi_card(title, value, subtitle="", color=COLOR_ENERGY):
    return html.Div([
        html.Div(title, style={"fontSize": "13px", "color": "#666", "fontWeight": "600",
                                "textTransform": "uppercase"}),
        html.Div(value, style={"fontSize": "28px", "fontWeight": "bold", "color": color}),
        html.Div(subtitle, style={"fontSize": "12px", "color": "#888"}),
    ], style={"flex": "1", "padding": "16px 20px", "backgroundColor": "white",
              "borderRadius": "10px", "boxShadow": "0 1px 4px rgba(0,0,0,0.12)",
              "margin": "0 8px", "minWidth": "180px"})


kpi_row = html.Div([
    kpi_card("Total Energy", f"{kpi.get('total_energy_kwh', 0):,.0f} kWh",
             f"{kpi.get('date_range_start', '')[:10]} → {kpi.get('date_range_end', '')[:10]}",
             COLOR_ENERGY),
    kpi_card("Average Power", f"{kpi.get('average_power_kw', kpi.get('average_energy_kw', 0)):.3f} kW",
             "Average power", COLOR_ENERGY),
    kpi_card("Peak Consumption", f"{kpi.get('peak_consumption_kw', 0):.2f} kW",
             f"At {kpi.get('peak_consumption_time', 'N/A')}", COLOR_SOLAR),
    kpi_card("Number of Anomalies", f"{kpi.get('number_of_anomalies', 0):,}",
             f"{kpi.get('anomaly_rate_pct', 0)}% of total data", COLOR_ANOMALY),
], style={"display": "flex", "flexWrap": "wrap", "marginBottom": "20px"})


# ==========================================================
# 10. LAYOUT
# ==========================================================

def chart_card(fig, width="50%"):
    return html.Div([dcc.Graph(figure=fig)],
                     style={"width": width, "display": "inline-block", "padding": "6px",
                            "boxSizing": "border-box"})


app.layout = html.Div([
    html.H1("Smart Home Anomaly Detection Dashboard",
            style={"textAlign": "center"}),
    html.P(model_status, style={"textAlign": "center",
                                "color": "green" if model is not None else "darkorange"}),
    html.P(data_status, style={"textAlign": "center", "color": "darkorange"})
    if data_status else html.Div(),

    # ----- KPI CARDS -----
    html.H3("Overview Metrics (KPI Cards)", style={"marginTop": "10px"}),
    kpi_row,

    # ----- ALERT PANEL -----
    html.H3("Anomaly Alerts (Alert Panel)"),
    html.Div(alert_cards, style={"marginBottom": "20px"}),

    # ----- PREDICTION + AI -----
    html.Div([
        html.H3("Anomaly Check and AI Analysis"),
        html.P("Leakage-free model inputs; total appliance power is kept only as AI context."),
        html.Label("Temperature (°F): "),
        dcc.Input(id="input-temp", type="number", value=75, step=1),
        html.Label("   Humidity (0-1): "),
        dcc.Input(id="input-humidity", type="number", value=0.5, step=0.01, min=0, max=1),
        html.Label("   Current Solar Generation (kW): "),
        dcc.Input(id="input-gen", type="number", value=0.0, step=0.05, min=0),
        html.Br(), html.Br(),
        html.Label("Total Appliance Power (kW): "),
        dcc.Input(id="input-appliance", type="number", value=2, step=0.1, min=0),
        html.Label("   Hour (0-23): "),
        dcc.Input(id="input-hour", type="number", value=12, step=1, min=0, max=23),
        html.Label("   Day of Week (0=Mon ... 6=Sun): "),
        dcc.Input(id="input-dow", type="number", value=0, step=1, min=0, max=6),
        html.Label("   Month (1-12): "),
        dcc.Input(id="input-month", type="number", value=6, step=1, min=1, max=12),
        html.Br(), html.Br(),
        html.Button("Predict and Ask AI", id="predict-btn", n_clicks=0,
                    style={"fontSize": "16px", "padding": "10px"}),
        html.Div(id="prediction-output",
                 style={"marginTop": "20px", "fontWeight": "bold", "fontSize": "20px"}),
        html.Div(id="ai-output",
                 style={"marginTop": "10px", "padding": "10px",
                        "backgroundColor": "#e8f4f8", "borderRadius": "5px"}),
    ], style={"padding": "20px", "backgroundColor": "#f0f0f0",
              "marginBottom": "20px", "borderRadius": "10px"}),

    # ----- CHARTS -----
    html.H3("Analysis Charts"),
    html.Div([
        chart_card(fig_line),
        chart_card(fig_area),
        chart_card(fig_top5),
        chart_card(fig_pie),
        chart_card(fig_hourly),
        chart_card(fig_dow),
    ]),

    # ----- SMART CITY RECOMMENDATIONS -----
    html.H3("Energy-Saving Suggestions (Smart City Recommendation)"),
    html.Ul([html.Li(r) for r in recommendations],
            style={"backgroundColor": "#EAF7EE", "padding": "16px 30px",
                  "borderRadius": "10px", "lineHeight": "1.6"}),
], style={"fontFamily": "Arial, sans-serif", "padding": "20px"})


# ---------- 11. Callbacks ----------
@app.callback(
    [Output("prediction-output", "children"),
     Output("ai-output", "children")],
    [Input("predict-btn", "n_clicks")],
    [State("input-temp", "value"),
     State("input-humidity", "value"),
     State("input-gen", "value"),
     State("input-appliance", "value"),
     State("input-hour", "value"),
     State("input-dow", "value"),
     State("input-month", "value")],
)
def update_prediction(n_clicks, temp, humidity, gen_kw, appliance, hour, dayofweek, month):
    if not n_clicks:
        return "", ""

    dayofweek = int(dayofweek or 0)
    user_inputs = {
        "temperature": temp,
        "humidity": humidity,
        "gen_kw": gen_kw,
        "total_appliance": appliance,
        "hour": hour,
        "dayofweek": dayofweek,
        "month": month,
        "is_weekend": int(dayofweek >= 5),
    }
    try:
        pred, score = predict_anomaly(user_inputs)
        text_result = ("RESULT: ANOMALOUS" if pred == 1 else "RESULT: NORMAL")
        text_result += f" - score={score:.3f}, threshold={decision_threshold:.3f}"
        ai_text = get_ai_explanation(pred, temp, appliance)
        return text_result, ai_text
    except Exception as exc:
        return f"Prediction failed: {exc}", "Please check the input values and model artifacts."


# ---------- 12. Run the app (Dash 3.x: use app.run, NOT app.run_server) ----------
if __name__ == "__main__":
    app.run(debug=True)
